優化環境設定的腳本並且新增了doctor@k7
ntut-xuan/NuOJ-Sandbox pull request #55
Opened 2023-04-07 17:26 UTC by royis87

2023-04-09 04:41 UTC, ntut-xuan requested changes
建議修改這些東西。

2023-04-09 04:41 UTC, ntut-xuan commented on backend/env_doctor.sh
> +            echo "[  FAIL  ] ASLR"
建議使用全名而非縮寫，以利於使用者來得知哪裡出現問題。

例如：`[    FAIL    ] Address Space Layout Randomization`
另外，有考慮加入成因嗎，例如在 `FAIL` 的時候，呈現一段字告訴使用者為什麼會失敗、可能的原因是什麼、以及怎麼解決。

2023-04-09 04:41 UTC, ntut-xuan commented on backend/env_doctor.sh
> +            echo "[  FAIL  ] THP"
建議使用全名而非縮寫，以利於使用者來得知哪裡出現問題。

例如：`[    FAIL    ] Transparent Hugepage Support`
另外，有考慮加入成因嗎，例如在 FAIL 的時候，呈現一段字告訴使用者為什麼會失敗、可能的原因是什麼、以及怎麼解決。

2023-05-21 16:01 UTC, royis87 commented on backend/env_doctor.sh
> +            echo "[  FAIL  ] ASLR"
報告老大 我覺得沒必要，因為我們會要求使用者先跑 env_setting，如果還是出錯，我們也沒辦法提供什麼建議。

2023-05-21 16:01 UTC, royis87 commented on backend/env_doctor.sh
> +            echo "[  FAIL  ] THP"
報告老大 我覺得沒必要，因為我們會要求使用者先跑 env_setting，如果還是出錯，我們也沒辦法提供什麼建議。

2023-05-21 23:28 UTC, ntut-xuan commented
Change base into develope & Merge develope

2023-05-22 00:41 UTC, ntut-xuan approved these changes
LGTM.

2023-05-22 00:42 UTC, merged